sudo: required
services: 
  - docker
before_install:
  - docker build -t francoeduardo/docker-react -f Dockerfile.dev .
script:
 - docker run  -e CI=true francoeduardo/docker-react npm run test
 
deploy: 
  provider: elasticbeanstalk
  region: "your region"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket_name: "your bucket name"
  bucket_path: "docker-react"
  on: 
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
